"use client";

import { useCallback, useEffect, useState } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Building2, ClipboardCheck, Eye, LayoutGrid, List, Loader2, Pencil, Plus, RotateCcw, Trash2, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { ConfirmDialog } from "@/components/shared/confirm-dialog";

type Company = { id: string; razaoSocial: string; nomeFantasia?: string | null; isDefault?: boolean };
type FormState = { numero: string; companyId: string; dataEmissao: string; status: "Rascunho" | "Finalizado"; clienteCodigo: string; clienteNome: string; clienteFantasia: string; clienteEndereco: string; clienteNumero: string; clienteBairro: string; clienteCidade: string; clienteUf: string; clienteTelefone: string; clienteDocumento: string; equipamento: string; numeroSerie: string; modelo: string; equipamentoObservacao: string; problema: string; problemaRelatado: string; problemasEncontrados: string; procedimentosRealizados: string; conclusao: string };
type Report = FormState & { id: string; createdAt: string; createdByUser: { name: string }; company: Company };
type Filters = { numero: string; cliente: string; companyId: string; status: string; dataInicial: string; dataFinal: string };
const today = () => new Date().toISOString().slice(0, 10);
const blank: FormState = { numero: "", companyId: "", dataEmissao: today(), status: "Rascunho", clienteCodigo: "", clienteNome: "", clienteFantasia: "", clienteEndereco: "", clienteNumero: "", clienteBairro: "", clienteCidade: "", clienteUf: "", clienteTelefone: "", clienteDocumento: "", equipamento: "", numeroSerie: "", modelo: "", equipamentoObservacao: "", problema: "", problemaRelatado: "", problemasEncontrados: "", procedimentosRealizados: "", conclusao: "" };
const emptyFilters: Filters = { numero: "", cliente: "", companyId: "all", status: "all", dataInicial: "", dataFinal: "" };

function StatusBadge({ status }: { status: FormState["status"] }) { return <Badge variant="outline" className={status === "Finalizado" ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-amber-300 bg-amber-50 text-amber-800"}>{status}</Badge>; }

export default function TechnicalReportsPage() {
  const router = useRouter();
  const { data: session } = useSession();
  const isAdmin = session?.user?.role === "ADMIN";
  const [items, setItems] = useState<Report[]>([]); const [companies, setCompanies] = useState<Company[]>([]);
  const [filters, setFilters] = useState<Filters>(emptyFilters); const [viewMode, setViewMode] = useState<"table" | "grid">("table");
  const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [editing] = useState<Report | null>(null);
  const [form, setForm] = useState<FormState>(blank); const [saving, setSaving] = useState(false); const [deleting, setDeleting] = useState<Report | null>(null);

  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem("laudos:filtros") || "null"); if (saved) setFilters({ ...emptyFilters, ...saved }); } catch { /* ignora */ } setViewMode(localStorage.getItem("laudos:visualizacao") === "grid" ? "grid" : "table"); }, []);
  useEffect(() => { localStorage.setItem("laudos:filtros", JSON.stringify(filters)); }, [filters]);
  useEffect(() => { localStorage.setItem("laudos:visualizacao", viewMode); }, [viewMode]);
  const load = useCallback(async () => { setLoading(true); try { const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value && value !== "all") params.set(key, value); }); const response = await fetch(`/api/technical-reports?${params}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Erro ao carregar laudos"); setItems(body); } catch (error) { toast.error(error instanceof Error ? error.message : "Erro ao carregar laudos"); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { const timeout = window.setTimeout(load, 250); return () => window.clearTimeout(timeout); }, [load]);
  useEffect(() => { fetch("/api/companies").then((response) => response.json()).then((data: Company[]) => { setCompanies(data); setForm((current) => ({ ...current, companyId: current.companyId || data.find((company) => company.isDefault)?.id || data[0]?.id || "" })); }).catch(() => toast.error("Erro ao carregar empresas")); }, []);
  function field<K extends keyof FormState>(key: K, value: FormState[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function filter(key: keyof Filters, value: string) { setFilters((current) => ({ ...current, [key]: value })); }
  function showForm(item?: Report) { router.push(item ? `/laudos/${item.id}` : "/laudos/novo"); }
  async function save() { if (!form.companyId || !form.clienteNome.trim() || !form.equipamento.trim()) return toast.error("Informe empresa, cliente e equipamento"); setSaving(true); try { const response = await fetch(editing ? `/api/technical-reports/${editing.id}` : "/api/technical-reports", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Erro ao salvar laudo"); toast.success(editing ? "Laudo atualizado" : `Laudo Nº ${body.numero} criado`); setOpen(false); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Erro ao salvar laudo"); } finally { setSaving(false); } }
  const actions = (item: Report) => <div className="flex gap-1"><Button variant="ghost" size="icon-sm" title="Visualizar e imprimir" onClick={() => router.push(`/laudos/${item.id}/imprimir`)}><Eye className="h-4 w-4" /></Button><Button variant="ghost" size="icon-sm" title="Editar" onClick={() => showForm(item)}><Pencil className="h-4 w-4" /></Button>{isAdmin && <Button variant="ghost" size="icon-sm" className="text-destructive" title="Excluir" onClick={() => setDeleting(item)}><Trash2 className="h-4 w-4" /></Button>}</div>;

  return <div className="space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-2"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><ClipboardCheck className="h-6 w-6 text-primary" /> Laudos Técnicos</h1><p className="text-sm text-muted-foreground">Cadastro, emissão e histórico dos laudos de equipamentos.</p></div><div className="flex items-center gap-2"><div className="flex items-center rounded-md border p-0.5"><Button variant={viewMode === "table" ? "secondary" : "ghost"} size="icon" title="Visualizar em tabela" onClick={() => setViewMode("table")}><List className="h-4 w-4" /></Button><Button variant={viewMode === "grid" ? "secondary" : "ghost"} size="icon" title="Visualizar em cartões" onClick={() => setViewMode("grid")}><LayoutGrid className="h-4 w-4" /></Button></div><Button onClick={() => showForm()}><Plus className="mr-2 h-4 w-4" /> Novo laudo</Button></div></div>
    <Card><CardContent className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-6"><Input placeholder="Número" value={filters.numero} onChange={(e) => filter("numero", e.target.value)} /><Input placeholder="Cliente" value={filters.cliente} onChange={(e) => filter("cliente", e.target.value)} /><Select value={filters.companyId} onValueChange={(value) => value && filter("companyId", value)}><SelectTrigger><SelectValue>{(value) => value === "all" ? "Todas as empresas" : companies.find((company) => company.id === value)?.nomeFantasia || companies.find((company) => company.id === value)?.razaoSocial || "Empresa"}</SelectValue></SelectTrigger><SelectContent><SelectItem value="all">Todas as empresas</SelectItem>{companies.map((company) => <SelectItem key={company.id} value={company.id}>{company.nomeFantasia || company.razaoSocial}</SelectItem>)}</SelectContent></Select><Select value={filters.status} onValueChange={(value) => value && filter("status", value)}><SelectTrigger><SelectValue>{(value) => value === "all" ? "Todos os status" : value}</SelectValue></SelectTrigger><SelectContent><SelectItem value="all">Todos os status</SelectItem><SelectItem value="Rascunho">Rascunho</SelectItem><SelectItem value="Finalizado">Finalizado</SelectItem></SelectContent></Select><Input type="date" value={filters.dataInicial} onChange={(e) => filter("dataInicial", e.target.value)} /><Input type="date" value={filters.dataFinal} onChange={(e) => filter("dataFinal", e.target.value)} /><div className="flex justify-end sm:col-span-2 lg:col-span-6"><Button variant="outline" size="sm" onClick={() => setFilters(emptyFilters)}><RotateCcw className="mr-2 h-4 w-4" /> Limpar filtros</Button></div></CardContent></Card>
    {loading ? <Card><CardContent className="py-16"><Loader2 className="mx-auto h-7 w-7 animate-spin text-primary" /></CardContent></Card> : viewMode === "grid" ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.length === 0 ? <p className="col-span-full py-12 text-center text-muted-foreground">Nenhum laudo encontrado.</p> : items.map((item) => <Card key={item.id} className="flex h-full flex-col overflow-hidden border-l-4 border-l-primary shadow-sm"><CardHeader className="border-b bg-gradient-to-r from-primary/10 via-primary/5 to-transparent pb-3"><CardTitle className="flex items-center justify-between text-base"><span>Nº {item.numero}</span><span className="text-sm font-normal text-muted-foreground">{new Date(item.dataEmissao).toLocaleDateString("pt-BR", { timeZone: "UTC" })}</span></CardTitle></CardHeader><CardContent className="flex flex-1 flex-col space-y-3 pt-4 text-sm"><StatusBadge status={item.status} /><div className="space-y-2 rounded-xl bg-muted/35 p-3"><p><UserRound className="mr-1.5 inline h-3.5 w-3.5 text-primary" /><span className="text-muted-foreground">Cliente:</span> {item.clienteNome}</p><p><Building2 className="mr-1.5 inline h-3.5 w-3.5 text-primary" /><span className="text-muted-foreground">Empresa:</span> {item.company.nomeFantasia || item.company.razaoSocial}</p><p><span className="text-muted-foreground">Equipamento:</span> {item.equipamento}</p><p><span className="text-muted-foreground">Técnico:</span> {item.createdByUser?.name || "—"}</p></div><div className="mt-auto flex justify-end border-t pt-2">{actions(item)}</div></CardContent></Card>)}</div> : <Card><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Número</TableHead><TableHead>Cliente</TableHead><TableHead>Equipamento</TableHead><TableHead>Empresa</TableHead><TableHead>Data</TableHead><TableHead>Técnico</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Ações</TableHead></TableRow></TableHeader><TableBody>{items.length === 0 ? <TableRow><TableCell colSpan={8} className="py-12 text-center text-muted-foreground">Nenhum laudo encontrado.</TableCell></TableRow> : items.map((item) => <TableRow key={item.id}><TableCell className="font-bold">{item.numero}</TableCell><TableCell>{item.clienteNome}</TableCell><TableCell><p className="font-medium">{item.equipamento}</p><p className="text-xs text-muted-foreground">{item.modelo || "Modelo não informado"}</p></TableCell><TableCell>{item.company.nomeFantasia || item.company.razaoSocial}</TableCell><TableCell>{new Date(item.dataEmissao).toLocaleDateString("pt-BR", { timeZone: "UTC" })}</TableCell><TableCell>{item.createdByUser?.name || "—"}</TableCell><TableCell><StatusBadge status={item.status} /></TableCell><TableCell><div className="flex justify-end">{actions(item)}</div></TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[94vh] w-[96vw] max-w-[96vw] overflow-y-auto sm:max-w-[1600px]"><DialogHeader><DialogTitle>{editing ? `Editar laudo Nº ${editing.numero}` : "Novo laudo técnico"}</DialogTitle><DialogDescription>Preencha as informações do cliente, equipamento, diagnóstico e conclusão.</DialogDescription></DialogHeader><div className="grid gap-3 py-2 md:grid-cols-4">
      <div className="space-y-2"><Label>Número do laudo</Label><Input maxLength={30} value={form.numero} onChange={(e) => field("numero", e.target.value)} placeholder="Deixe em branco para gerar automático" /></div><div className="space-y-2"><Label>Empresa emissora *</Label><Select value={form.companyId} onValueChange={(value) => value && field("companyId", value)}><SelectTrigger><SelectValue>{(value) => companies.find((company) => company.id === value)?.razaoSocial || "Selecione"}</SelectValue></SelectTrigger><SelectContent>{companies.map((company) => <SelectItem key={company.id} value={company.id}>{company.razaoSocial}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Data *</Label><Input type="date" value={form.dataEmissao.slice(0, 10)} onChange={(event) => field("dataEmissao", event.target.value)} /></div><div className="space-y-2"><Label>Status</Label><Select value={form.status} onValueChange={(value) => value && field("status", value as FormState["status"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Rascunho">Rascunho</SelectItem><SelectItem value="Finalizado">Finalizado</SelectItem></SelectContent></Select></div>
      <h3 className="border-b pb-1 font-semibold md:col-span-4">Dados do cliente</h3><div className="space-y-2"><Label>Código</Label><Input value={form.clienteCodigo} onChange={(e) => field("clienteCodigo", e.target.value)} /></div><div className="space-y-2 md:col-span-2"><Label>Cliente *</Label><Input value={form.clienteNome} onChange={(e) => field("clienteNome", e.target.value)} /></div><div className="space-y-2"><Label>Nome fantasia</Label><Input value={form.clienteFantasia} onChange={(e) => field("clienteFantasia", e.target.value)} /></div><div className="space-y-2 md:col-span-2"><Label>Endereço</Label><Input value={form.clienteEndereco} onChange={(e) => field("clienteEndereco", e.target.value)} /></div><div className="space-y-2"><Label>Número</Label><Input value={form.clienteNumero} onChange={(e) => field("clienteNumero", e.target.value)} /></div><div className="space-y-2"><Label>Bairro</Label><Input value={form.clienteBairro} onChange={(e) => field("clienteBairro", e.target.value)} /></div><div className="space-y-2"><Label>Cidade</Label><Input value={form.clienteCidade} onChange={(e) => field("clienteCidade", e.target.value)} /></div><div className="space-y-2"><Label>UF</Label><Input maxLength={2} value={form.clienteUf} onChange={(e) => field("clienteUf", e.target.value.toUpperCase())} /></div><div className="space-y-2"><Label>Telefone</Label><Input value={form.clienteTelefone} onChange={(e) => field("clienteTelefone", e.target.value)} /></div><div className="space-y-2"><Label>CPF/CNPJ</Label><Input value={form.clienteDocumento} onChange={(e) => field("clienteDocumento", e.target.value)} /></div>
      <h3 className="border-b pb-1 font-semibold md:col-span-4">Dados do equipamento</h3><div className="space-y-2 md:col-span-2"><Label>Equipamento *</Label><Input value={form.equipamento} onChange={(e) => field("equipamento", e.target.value)} /></div><div className="space-y-2"><Label>Número de série</Label><Input value={form.numeroSerie} onChange={(e) => field("numeroSerie", e.target.value)} /></div><div className="space-y-2"><Label>Modelo</Label><Input value={form.modelo} onChange={(e) => field("modelo", e.target.value)} /></div><div className="space-y-2 md:col-span-2"><Label>Problema</Label><Input value={form.problema} onChange={(e) => field("problema", e.target.value)} /></div><div className="space-y-2 md:col-span-2"><Label>Observação do equipamento</Label><Input value={form.equipamentoObservacao} onChange={(e) => field("equipamentoObservacao", e.target.value)} /></div>
      <div className="space-y-2 md:col-span-4"><Label>Problema relatado</Label><Textarea rows={3} value={form.problemaRelatado} onChange={(e) => field("problemaRelatado", e.target.value)} /></div><div className="space-y-2 md:col-span-2"><Label>Problemas encontrados</Label><Textarea rows={6} value={form.problemasEncontrados} onChange={(e) => field("problemasEncontrados", e.target.value)} /></div><div className="space-y-2 md:col-span-2"><Label>Procedimentos realizados</Label><Textarea rows={6} value={form.procedimentosRealizados} onChange={(e) => field("procedimentosRealizados", e.target.value)} /></div><div className="space-y-2 md:col-span-4"><Label>Conclusão do laudo</Label><Textarea rows={5} value={form.conclusao} onChange={(e) => field("conclusao", e.target.value)} placeholder="Informe o parecer e a conclusão final do técnico" /></div>
      <div className="flex justify-end gap-2 md:col-span-4"><Button variant="outline" onClick={() => setOpen(false)}>Cancelar</Button><Button disabled={saving} onClick={save}>{saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Salvar laudo</Button></div>
    </div></DialogContent></Dialog>
    <ConfirmDialog open={!!deleting} onOpenChange={(value) => !value && setDeleting(null)} title="Excluir este laudo?" description="O laudo será removido permanentemente." confirmLabel="Excluir" variant="destructive" onConfirm={async () => { if (!deleting) return; const response = await fetch(`/api/technical-reports/${deleting.id}`, { method: "DELETE" }); if (response.ok) { toast.success("Laudo excluído"); await load(); } else toast.error("Erro ao excluir laudo"); setDeleting(null); }} />
  </div>;
}
