"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useSession } from "next-auth/react";
import { toast } from "sonner";
import { useDeleteSupplierQuotation, useSupplierQuotations, useSuppliers } from "@/hooks/use-supplier-quotations";
import { supplierQuotationStatuses } from "@/lib/supplier-quotation-validation";
import { Button, buttonVariants } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Eye, FilePlus2, Grid2X2, List, Pencil, Printer, Search, ShoppingCart, Trash2, X } from "lucide-react";
import { formatCurrencyBRL } from "@/lib/format";
import { ConfirmDialog } from "@/components/shared/confirm-dialog";

const labels = { Rascunho: "Rascunho", EmCotacao: "Em cotação", Recebida: "Recebida", Aprovada: "Aprovada", NaoAprovada: "Não aprovada", Finalizada: "Finalizada" } as const;
const colors: Record<string, string> = { Rascunho: "bg-slate-100 text-slate-700", EmCotacao: "bg-amber-100 text-amber-800", Recebida: "bg-blue-100 text-blue-800", Aprovada: "bg-emerald-100 text-emerald-800", NaoAprovada: "bg-red-100 text-red-800", Finalizada: "bg-violet-100 text-violet-800" };

export default function SupplierQuotationsPage() {
  const { data: session } = useSession();
  const suppliers = useSuppliers();
  const [view, setView] = useState<"table" | "grid">("table");
  const [filters, setFilters] = useState({ numero: "", referencia: "", supplierId: "", status: "", tipo: "", dataInicial: "", dataFinal: "" });
  const { data = [], isLoading } = useSupplierQuotations(filters);
  const [pendingDelete, setPendingDelete] = useState<(typeof data)[number] | null>(null);
  const remove = useDeleteSupplierQuotation();
  const admin = session?.user?.role === "ADMIN";
  useEffect(() => { setView(window.localStorage.getItem("supplier-quotation-view") === "grid" ? "grid" : "table"); }, []);
  function changeView(next: "table" | "grid") { setView(next); window.localStorage.setItem("supplier-quotation-view", next); }
  function change(key: keyof typeof filters, value: string) { setFilters(current => ({ ...current, [key]: value })); }
  function supplierNames(quotation: (typeof data)[number]) { return quotation.tipo === "FornecedorUnico" ? quotation.primarySupplier?.razaoSocial || "—" : Array.from(new Set(quotation.itens.map(item => item.supplier.razaoSocial))).join(", ") || "—"; }
  async function deleteQuotation() { if (!pendingDelete) return; try { await remove.mutateAsync(pendingDelete.id); toast.success("Cotação excluída"); setPendingDelete(null); } catch (error) { toast.error(error instanceof Error ? error.message : "Erro ao excluir"); } }
  const actions = (quotation: (typeof data)[number]) => <div className="flex justify-end"><Link className={buttonVariants({ variant: "ghost", size: "icon" })} href={`/cotacoes/${quotation.id}`} title="Visualizar"><Eye /></Link>{quotation.status !== "Finalizada" && <Link className={buttonVariants({ variant: "ghost", size: "icon" })} href={`/cotacoes/${quotation.id}`} title="Editar"><Pencil /></Link>}<Link className={buttonVariants({ variant: "ghost", size: "icon" })} href={`/cotacoes/${quotation.id}/imprimir`} title="Imprimir"><Printer /></Link>{admin && <Button variant="ghost" size="icon" onClick={() => setPendingDelete(quotation)}><Trash2 className="text-destructive" /></Button>}</div>;

  return <div className="space-y-6 p-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><ShoppingCart className="h-6 w-6 text-primary" />Cotações de Fornecedores</h1><p className="text-sm text-muted-foreground">Histórico das listas internas de compras.</p></div><div className="flex gap-2"><div className="flex rounded-lg border p-1"><Button variant={view === "table" ? "secondary" : "ghost"} size="icon-sm" onClick={() => changeView("table")} title="Tabela"><List /></Button><Button variant={view === "grid" ? "secondary" : "ghost"} size="icon-sm" onClick={() => changeView("grid")} title="Cards"><Grid2X2 /></Button></div><Link className={buttonVariants()} href="/cotacoes/novo"><FilePlus2 />Nova cotação</Link></div></div>
    <div className="rounded-2xl border bg-card p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-7"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder="Número" value={filters.numero} onChange={event => change("numero", event.target.value)} /></div><Input placeholder="Referência" value={filters.referencia} onChange={event => change("referencia", event.target.value)} /><Select value={filters.supplierId || "all"} onValueChange={value => change("supplierId", !value || value === "all" ? "" : value)}><SelectTrigger><SelectValue>{value => value === "all" ? "Todos fornecedores" : suppliers.data?.find(supplier => supplier.id === value)?.razaoSocial || "Todos fornecedores"}</SelectValue></SelectTrigger><SelectContent><SelectItem value="all">Todos fornecedores</SelectItem>{suppliers.data?.map(supplier => <SelectItem key={supplier.id} value={supplier.id}>{supplier.razaoSocial}</SelectItem>)}</SelectContent></Select><Select value={filters.tipo || "all"} onValueChange={value => change("tipo", !value || value === "all" ? "" : value)}><SelectTrigger><SelectValue>{value => value === "FornecedorUnico" ? "Fornecedor único" : value === "MultiplosFornecedores" ? "Vários fornecedores" : "Todos os tipos"}</SelectValue></SelectTrigger><SelectContent><SelectItem value="all">Todos os tipos</SelectItem><SelectItem value="FornecedorUnico">Fornecedor único</SelectItem><SelectItem value="MultiplosFornecedores">Vários fornecedores</SelectItem></SelectContent></Select><Select value={filters.status || "all"} onValueChange={value => change("status", !value || value === "all" ? "" : value)}><SelectTrigger><SelectValue>{value => value === "all" ? "Todos os status" : labels[value as keyof typeof labels] || "Todos os status"}</SelectValue></SelectTrigger><SelectContent><SelectItem value="all">Todos os status</SelectItem>{supplierQuotationStatuses.map(status => <SelectItem key={status} value={status}>{labels[status]}</SelectItem>)}</SelectContent></Select><Input type="date" value={filters.dataInicial} onChange={event => change("dataInicial", event.target.value)} /><div className="flex gap-2"><Input type="date" value={filters.dataFinal} onChange={event => change("dataFinal", event.target.value)} /><Button variant="outline" size="icon" onClick={() => setFilters({ numero: "", referencia: "", supplierId: "", status: "", tipo: "", dataInicial: "", dataFinal: "" })}><X /></Button></div></div></div>
    {view === "table" ? <div className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-muted/40 text-left"><tr><th className="p-4">Número</th><th className="p-4">Data</th><th className="p-4">Referência</th><th className="p-4">Fornecedor(es)</th><th className="p-4">Criado por</th><th className="p-4">Tipo</th><th className="p-4">Status</th><th className="p-4 text-right">Total</th><th className="p-4 text-right">Ações</th></tr></thead><tbody>{data.map(quotation => <tr key={quotation.id} className="border-t"><td className="p-4 font-semibold">{quotation.numero}</td><td className="p-4">{new Date(quotation.dataCotacao).toLocaleDateString("pt-BR")}</td><td className="p-4">{quotation.referencia || "—"}</td><td className="p-4">{supplierNames(quotation)}</td><td className="p-4">{quotation.createdByUser?.name || "—"}</td><td className="p-4">{quotation.tipo === "FornecedorUnico" ? "Único" : "Vários"}</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-xs ${colors[quotation.status]}`}>{labels[quotation.status]}</span></td><td className="p-4 text-right font-semibold">{formatCurrencyBRL(Number(quotation.total))}</td><td className="p-4">{actions(quotation)}</td></tr>)}{!isLoading && !data.length && <tr><td colSpan={9} className="p-12 text-center text-muted-foreground">Nenhuma cotação encontrada.</td></tr>}</tbody></table></div></div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.map(quotation => <article key={quotation.id} className="rounded-2xl border border-t-4 border-t-primary bg-card p-5 shadow-sm"><div className="flex justify-between"><strong>Nº {quotation.numero}</strong><span className={`rounded-full px-2.5 py-1 text-xs ${colors[quotation.status]}`}>{labels[quotation.status]}</span></div><p className="mt-4 text-sm"><span className="text-muted-foreground">Fornecedor:</span> {supplierNames(quotation)}</p><p className="mt-1 text-sm"><span className="text-muted-foreground">Referência:</span> {quotation.referencia || "—"}</p><p className="mt-1 text-sm"><span className="text-muted-foreground">Criado por:</span> {quotation.createdByUser?.name || "—"}</p><p className="mt-1 text-sm"><span className="text-muted-foreground">Data:</span> {new Date(quotation.dataCotacao).toLocaleDateString("pt-BR")}</p><p className="mt-4 text-xl font-bold text-primary">{formatCurrencyBRL(Number(quotation.total))}</p><div className="mt-4 border-t pt-2">{actions(quotation)}</div></article>)}{!isLoading && !data.length && <p className="col-span-full py-12 text-center text-muted-foreground">Nenhuma cotação encontrada.</p>}</div>}
    <ConfirmDialog open={!!pendingDelete} onOpenChange={open => !open && setPendingDelete(null)} title="Excluir cotação?" description={pendingDelete ? `A cotação ${pendingDelete.numero} será excluída permanentemente.` : ""} confirmLabel="Excluir" variant="destructive" onConfirm={deleteQuotation} />
  </div>;
}
