"use client";

import { useState } from "react";
import Link from "next/link";
import { useSession } from "next-auth/react";
import { toast } from "sonner";
import { useDeleteSupplierQuotation, useSupplierQuotations, useSuppliers } from "@/hooks/use-supplier-quotations";
import { supplierQuotationStatuses } from "@/lib/supplier-quotation-validation";
import { Button, buttonVariants } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Eye, FilePlus2, Pencil, Printer, Search, ShoppingCart, Trash2, X } from "lucide-react";
import { formatCurrencyBRL } from "@/lib/format";

const labels = { Rascunho: "Rascunho", EmCotacao: "Em cotação", Recebida: "Recebida", Aprovada: "Aprovada", NaoAprovada: "Não aprovada", Finalizada: "Finalizada" } as const;
const colors: Record<string, string> = { Rascunho: "bg-slate-100 text-slate-700", EmCotacao: "bg-amber-100 text-amber-800", Recebida: "bg-blue-100 text-blue-800", Aprovada: "bg-emerald-100 text-emerald-800", NaoAprovada: "bg-red-100 text-red-800", Finalizada: "bg-violet-100 text-violet-800" };

export default function SupplierQuotationsPage() {
  const { data: session } = useSession(); const suppliers = useSuppliers(); const [filters, setFilters] = useState({ numero: "", referencia: "", supplierId: "", status: "", tipo: "", dataInicial: "", dataFinal: "" });
  const { data = [], isLoading } = useSupplierQuotations(filters); const remove = useDeleteSupplierQuotation(); const admin = session?.user?.role === "ADMIN";
  const change = (key: keyof typeof filters, value: string) => setFilters(current => ({ ...current, [key]: value }));
  return <div className="space-y-6 p-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><ShoppingCart className="h-6 w-6 text-primary" />Cotações de Fornecedores</h1><p className="text-sm text-muted-foreground">Histórico e comparação das cotações de compras.</p></div><Link className={buttonVariants()} href="/cotacoes/novo"><FilePlus2 className="mr-2 h-4 w-4" />Nova cotação</Link></div>
    <div className="rounded-2xl border bg-card p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-7"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder="Número" value={filters.numero} onChange={e => change("numero", e.target.value)} /></div><Input placeholder="Referência" value={filters.referencia} onChange={e => change("referencia", e.target.value)} /><Select value={filters.supplierId || "all"} onValueChange={v => change("supplierId", !v || v === "all" ? "" : v)}><SelectTrigger><SelectValue placeholder="Fornecedor" /></SelectTrigger><SelectContent><SelectItem value="all">Todos fornecedores</SelectItem>{suppliers.data?.map(s => <SelectItem key={s.id} value={s.id}>{s.razaoSocial}</SelectItem>)}</SelectContent></Select><Select value={filters.tipo || "all"} onValueChange={v => change("tipo", !v || v === "all" ? "" : v)}><SelectTrigger><SelectValue placeholder="Tipo" /></SelectTrigger><SelectContent><SelectItem value="all">Todos os tipos</SelectItem><SelectItem value="FornecedorUnico">Fornecedor único</SelectItem><SelectItem value="MultiplosFornecedores">Vários fornecedores</SelectItem></SelectContent></Select><Select value={filters.status || "all"} onValueChange={v => change("status", !v || v === "all" ? "" : v)}><SelectTrigger><SelectValue placeholder="Status" /></SelectTrigger><SelectContent><SelectItem value="all">Todos os status</SelectItem>{supplierQuotationStatuses.map(s => <SelectItem key={s} value={s}>{labels[s]}</SelectItem>)}</SelectContent></Select><Input type="date" value={filters.dataInicial} onChange={e => change("dataInicial", e.target.value)} /><div className="flex gap-2"><Input type="date" value={filters.dataFinal} onChange={e => change("dataFinal", e.target.value)} /><Button type="button" variant="outline" size="icon" title="Limpar filtros" onClick={() => setFilters({ numero: "", referencia: "", supplierId: "", status: "", tipo: "", dataInicial: "", dataFinal: "" })}><X className="h-4 w-4" /></Button></div></div></div>
    <div className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-muted/40 text-left"><tr><th className="p-4">Número</th><th className="p-4">Data</th><th className="p-4">Referência</th><th className="p-4">Fornecedor(es)</th><th className="p-4">Tipo</th><th className="p-4">Status</th><th className="p-4 text-right">Total</th><th className="p-4 text-right">Ações</th></tr></thead><tbody>{data.map(q => { const supplierNames = q.tipo === "FornecedorUnico" ? q.primarySupplier?.razaoSocial : Array.from(new Set(q.itens.map(i => i.supplier.razaoSocial))).join(", "); return <tr key={q.id} className="border-t hover:bg-muted/20"><td className="p-4 font-semibold">{q.numero}</td><td className="p-4">{new Date(q.dataCotacao).toLocaleDateString("pt-BR")}</td><td className="max-w-64 truncate p-4">{q.referencia || "—"}</td><td className="max-w-72 truncate p-4">{supplierNames || "—"}</td><td className="p-4">{q.tipo === "FornecedorUnico" ? "Único" : "Vários"}</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${colors[q.status]}`}>{labels[q.status]}</span></td><td className="p-4 text-right font-semibold">{formatCurrencyBRL(Number(q.total))}</td><td className="p-4"><div className="flex justify-end"><Button asChild variant="ghost" size="icon"><Link href={`/cotacoes/${q.id}`} title="Visualizar/editar"><Eye className="h-4 w-4" /></Link></Button><Button asChild variant="ghost" size="icon"><Link href={`/cotacoes/${q.id}`} title="Editar"><Pencil className="h-4 w-4" /></Link></Button><Button asChild variant="ghost" size="icon"><Link href={`/cotacoes/${q.id}/imprimir`} title="Imprimir"><Printer className="h-4 w-4" /></Link></Button>{admin && <Button variant="ghost" size="icon" onClick={async () => { if (!confirm(`Excluir a cotação ${q.numero}?`)) return; try { await remove.mutateAsync(q.id); toast.success("Cotação excluída"); } catch (e) { toast.error(e instanceof Error ? e.message : "Erro ao excluir"); } }}><Trash2 className="h-4 w-4 text-destructive" /></Button>}</div></td></tr>; })}{!isLoading && !data.length && <tr><td colSpan={8} className="p-12 text-center text-muted-foreground">Nenhuma cotação encontrada.</td></tr>}</tbody></table></div></div>
  </div>;
}
